### ISSUE TITLE
Gulp build detects a ton of duplicates

### ISSUE THREAD

**Issue by mbalex99** [jimschubert/electron-angular-example#2]
Looks like gulp detects a ton of duplicates

`client/jspm_packages/npm/rx@2.5.1/ts/rx.d.ts(61,3): error TS2300: Duplicate identifier 'underlyingObservable'.
client/jspm_packages/npm/rx@2.5.1/ts/rx.d.ts(66,5): error TS2300: Duplicate identifier 'export='.
client/jspm_packages/npm/rx@2.5.1/ts/rx.experimental.d.ts(320,2): error TS2300: Duplicate identifier 'export='.
client/jspm_packages/npm/rx@2.5.1/ts/rx.joinpatterns.d.ts(59,2): error TS2300: Duplicate identifier 'export='.
client/jspm_packages/npm/rx@2.5.1/ts/rx.testing.d.ts(24,15): error TS2300: Duplicate identifier 'Recorded'.
client/jspm_packages/npm/rx@2.5.1/ts/rx.testing.d.ts(46,15): error TS2300: Duplicate identifier 'Subscription'.
client/jspm_packages/npm/rx@2.5.1/ts/rx.testing.d.ts(52,3): error TS2300: Duplicate identifier 'messages'.
client/jspm_packages/npm/rx@2.5.1/ts/rx.testing.d.ts(63,2): error TS2300: Duplicate identifier 'export='.
client/jspm_packages/npm/rx@2.5.1/ts/rx.time-lite.d.ts(10,3): error TS2300: Duplicate identifier 'value'.
client/jspm_packages/npm/rx@2.5.1/ts/rx.time-lite.d.ts(11,3): error TS2300: Duplicate identifier 'interval'.
client/jspm_packages/npm/rx@2.5.1/ts/rx.time-lite.d.ts(15,3): error TS2300: Duplicate identifier 'value'.
client/jspm_packages/npm/rx@2.5.1/ts/rx.time-lite.d.ts(16,3): error TS2300: Duplicate identifier 'timestamp'.
client/jspm_packages/npm/rx@2.5.1/ts/rx.time.d.ts(65,2): error TS2300: Duplicate identifier 'export='.
client/jspm_packages/npm/rx@2.5.1/ts/rx.virtualtime.d.ts(22,3): error TS2300: Duplicate identifier 'isEnabled'.
client/jspm_packages/npm/rx@2.5.1/ts/rx.virtualtime.d.ts(40,2): error TS2300: Duplicate identifier 'export='.`

**Comment by jimschubert** [comment]
Thanks. Checked in a fix to get rid of the errors. Haven't messed around with it to see if this breaks anything else, though.
